### ISSUE TITLE
Iskanje kvazi klike

### ISSUE THREAD

**Issue by aniiiim** [aniiiim/Problem-najvecjega-polnega-podgrafa#1]
Funkcijo za kvazi-kliko in bisekcijo imama zapisano, vendar v funkcijo za maksimalno psevdokliko ne znama dodati omejitev, da je le-ta velikosti največ k. Če dodamo omejitvi p.add_constraint(len(x) <= k) dobima napako, da spremenljivka linearnega programa ne pozna funkcije len(). Mislima da se nama tudi zaradi tega  bisekcija ne zaključi za grafa večje od 10. Pri n=10 nama je še vrnilo kvazikliko, za n>10 pa se program izvaja v neskončnost.

**Comment by jaanos** [comment]
Kot že rečeno, ob definiciji ILP še niso znane vrednosti, tako da ni mogoče uporabiti funkcij, kot so `len`. Namesto tega velikost dobita na isti način kot v ciljni funkciji, torej
```sage
p.add_constraint(sum(x[v] for v in C) <= k)
```

**Comment by vidamaver** [comment]
Sva popravili vendar nama še vedno noče prevesti. Pri bisekciji nama prav tako nekaj ne dela prav, imate morda kakšen predlog kaj bi lahko šlo narobe?

**Comment by vidamaver** [comment]
Oziroma za manjši n (na primer n = 10) nama max_k_psevdoklika vrača prazen seznam. Bisekcija pa se ne izvede.
